spring:
  application:
    name: monitoring

server:
  port: 8080

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,prometheus
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true


info:
  app:
    name: Monitoring
    version: 1.0.0